# Generated by Django 5.2.5 on 2025-08-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_car_drivers_alter_car_manufacturer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver"},
        ),
    ]
