# Generated by Django 5.2.5 on 2025-08-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0004_alter_car_options_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["last_name"], "verbose_name": "driver"},
        ),
    ]
